site_name: Aikido Fegersheim

theme:
  name: null

  custom_dir: 'material'

  language: 'fr'

  palette:
    primary: 'indigo'
    accent: 'indigo'

  font:
    text: 'Roboto'
    code: 'Roboto Mono'

  logo: 'images/logo4.gif'

  feature:
    tabs: true

  include_search_page: false

extra:
  social:
    - type: 'github'
      link: 'https://github.com/aikido-fegersheim'


